### ISSUE TITLE
css for login page

### ISSUE THREAD

**Issue by jessicamcg** [cwerness/pull-requests#3]
AS a user
I WANT to see a styled login page
SO THAT my eyes dont hurt

GIVEN I am a user
WHEN I visit the login page
THEN the css shouldnt be ugly

**Comment by cwerness** [comment]
I added some cool animations because I'm l33t as heck

**Comment by cwerness** [comment]
Got the CSS ironed out with dummy data. Should be good to go once the page itself is finalized.
